trigger:
- master

pool:
  name: MyLocalAgent

variables:
  buildConfiguration: 'Release'

jobs:

- job: preparation
  displayName: 'Preparation'
  steps:
  - checkout: self
    fetchDepth: 1
  - script: |
      echo Build ID: $(Build.BuildId)
      echo Branch: $(Build.SourceBranch)
      echo Configuration: $(buildConfiguration)
    displayName: 'Assess Parameters'

- job: build
  displayName: 'Build'
  dependsOn: preparation
  condition: succeeded()
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '**/*Tests*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'
  - task: DotNetCoreCLI@2
    displayName: 'Publish'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

- job: cleanup
  displayName: 'Cleanup'
  dependsOn: build
  condition: always()
  steps:
  - checkout: none
  - script: echo Pipeline finished. Cleaning up.
    displayName: 'Cleanup'